/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ApiJShop;

import java.util.Set;
import javax.ws.rs.core.Application;

/**
 *
 * @author vit
 */
@javax.ws.rs.ApplicationPath("ApiJShoP")
public class ApiController extends Application {

    @Override
    public Set<Class<?>> getClasses() {
        return getRestResourceClasses();
    }

    /**
     * Do not modify this method. It is automatically generated by NetBeans REST support.
     */
    private Set<Class<?>> getRestResourceClasses() {
        Set<Class<?>> resources = new java.util.HashSet<Class<?>>();
        resources.add(servicios.ProductoCategoriaFacadeREST.class);
        resources.add(servicios.CategoriaFacadeREST.class);
        resources.add(servicios.ProductoFacadeREST.class);
        resources.add(servicios.dominio.CategoriaREST.class);
        try {
            Class<?> jacksonProvider = Class.forName("org.codehaus.jackson.jaxrs.JacksonJsonProvider");
            resources.add(jacksonProvider);
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(getClass().getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        return resources;
    }
    
}
